# Generated by Django 4.1.7 on 2023-03-06 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="topic",
            field=models.CharField(
                choices=[
                    ("DIV", "Divorce and Breakup"),
                    ("REL", "Relationship and Courtship Journey"),
                    ("OCC", "Occupation and Career"),
                    ("PRE", "Pregnancy Experience"),
                    ("MAR", "Marriage Experience"),
                    ("INT", "Intimacy"),
                    ("WED", "Wedding"),
                    ("NEW", "Newlywed Experience"),
                    ("SIN", "Single Parenting"),
                    ("TTC", "TTC"),
                    ("SPI", "Religion/Spirituality"),
                    ("HEA", "Health"),
                    ("FAS", "Fashion"),
                    ("PAR", "Parental Journey"),
                    ("SOC", "Social Life"),
                    ("AID", "Aid and Help (Let Love Lead)"),
                    ("DIY", "Do It Yourself (DIY)"),
                ],
                default="REL",
                max_length=3,
            ),
        ),
    ]
