# Generated by Django 4.1.7 on 2023-05-05 16:37

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("posts", "0002_post_topic"),
    ]

    operations = [
        migrations.RenameField(
            model_name="post",
            old_name="author",
            new_name="user",
        ),
    ]
