# Generated by Django 4.1.7 on 2023-03-06 07:09

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("UserProfile", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="followers",
            field=models.ManyToManyField(
                blank=True, related_name="followed_by", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="following",
            field=models.ManyToManyField(
                blank=True, related_name="follow", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
